# Generated by Django 4.0.4 on 2022-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='course',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клещи'), (2, 'Глисты')], default=1, verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='order_date',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
    ]
