# Generated by Django 4.0.4 on 2022-05-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='order_date',
        ),
    ]
