# Generated by Django 4.0.4 on 2022-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='probability',
            field=models.FloatField(default=0.2),
        ),
    ]
