# Generated by Django 4.0.4 on 2022-05-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='prize_code',
            field=models.IntegerField(default=0),
        ),
    ]
