# Generated by Django 4.0.4 on 2022-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_reward_prize_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='required_for_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клещи'), (2, 'Глисты')], default=1, verbose_name='Обязательный приз для:'),
        ),
    ]
