# Generated by Django 4.0.4 on 2022-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_reward_required_for_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='required_for_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клещи'), (2, 'Глисты'), (3, 'Необязательный')], default=1, verbose_name='Обязательный приз для:'),
        ),
    ]
